version: "3"
services:
    hub:
        image: selenium/hub:4.10.0
        ports: 
        - 4444:4444
    chrome:
        image: selenium/node-chrome:4.10
        shm_size: '2g'
        depends_on:
        - hub
        deploy:
         replicas: 1
        env_file: my.env
    firefox:
        image: selenium/node-firefox:4.10
        depends_on:
        - hub
        deploy:
         replicas: 1
        env_file: my.env

